#!/bin/bash

set -ev

app_name="live"
local_image="travislive_$app_name" # Docker Compose removes dashes and expects the name to end with the build app name
quay_image=quay.io/travisci/travis-live;
branch=$(echo $TRAVIS_BRANCH | sed -e 's/\//-/g')
commit=${TRAVIS_COMMIT:0:7}

docker-compose build --build-arg bundle_gems__contribsys__com=$BUNDLE_GEMS__CONTRIBSYS__COM "$app_name";

docker login -u="$QUAY_ROBOT_HANDLE" -p="$QUAY_ROBOT_TOKEN" quay.io;

docker images;

docker tag $local_image $quay_image:$branch;
docker push $quay_image:$branch;

docker tag $local_image $quay_image:$commit;
docker push $quay_image:$commit;

if [ ${branch} = "master" ]; then
  docker tag $local_image $quay_image:latest;
  docker push $quay_image:$branch;
fi

exit 0;